### ISSUE TITLE
Бот прокачивает ловкость вместо выносливости

### ISSUE THREAD

**Issue by ObiiOne** [Doktrjegih/nomad_backend#32]
- [x]  бот после левел апа прокачал вместо выносливости ловкость

Status:
Name: autoplayer
Health: 14/15
Weapon: Old book of unfunny jokes (attack 100)
Drunk level: [▇▇▇▇▇▇▇▇ ] (89)
Attack: 109
Defence: 9
Endurance: 2
Strength: 1
Agility: 1
Luck: 1
Level: 3
Scores: 75 (next level 1440)
Total scores: 2275
Gold: 29
Active quests:
* Wet dog - 5 (2 left)
* test3 - 2 (1 left)
* Homeless guy - 3 (3 left)
Available stats points: 1

1 - endurance
2 - strength
3 - agility
4 - luck
0 - cancel
Agility has been increased! Current value: 2

**Comment by ObiiOne** [comment]
**итак. бота апнул 3 левел, ниже кусок игры от левелапа до бага и еще чуть-чуть** 

You're in the tavern
Drunk level: [▇▇▇▇▇▇▇▇▇ ] (90)
1 - go out
2 - take a beer
3 - take a steak
4 - check quests
5 - inventory
6 - get status
7 - exit game
NEW LEVEL!

Thanks! Your reward is: 25 coins and 300 XP

Hello stranger!
I need to clean this area from Homeless guys
Think 3 ones will be enough for now
Reward for this is 63 gold coins
Quest has been taken

You're in the tavern
Drunk level: [▇▇▇▇▇▇▇▇▇ ] (90)
1 - go out
2 - take a beer
3 - take a steak
4 - check quests
5 - inventory
6 - get status
7 - exit game

You're in the location "village" (peaceful)
Drunk level: [▇▇▇▇▇▇▇▇▇ ] (90)
1 - go forward
2 - enter tavern
3 - inventory
4 - get status
5 - exit game

You're in the location "village" (peaceful) 
You've met Carl
Drunk level: [▇▇▇▇▇▇▇▇ ] (89)
Random welcome phrase
1 - go forward
2 - inventory
3 - get status
4 - exit game

Status:
Name: autoplayer
Health: 14/15
Weapon: Old book of unfunny jokes (attack 100)
Drunk level: [▇▇▇▇▇▇▇▇ ] (89)
Attack: 109
Defence: 9
Endurance: 2
Strength: 1
Agility: 1
Luck: 1
Level: 3
Scores: 75 (next level 1440)
Total scores: 2275
Gold: 29
Active quests:
* Wet dog - 5 (2 left)
* test3 - 2 (1 left)
* Homeless guy - 3 (3 left)
Available stats points: 1

1 - endurance
2 - strength
3 - agility
4 - luck
0 - cancel
### Agility has been increased! Current value: 2

You're in the location "village" (peaceful) 
You've met Carl
Drunk level: [▇▇▇▇▇▇▇▇ ] (89)
Random welcome phrase
1 - go forward
2 - inventory
3 - get status
4 - exit game

You're in the location "village" (peaceful)
Drunk level: [▇▇▇▇▇▇▇▇ ] (88)
1 - go forward
2 - inventory
3 - get status
4 - exit game

1 - Beer bottle: 1
2 - Old rotten cudgel (attack 4): 1
3 - Old book of unfunny jokes (attack 100): 2 [active weapon]
4 - Old Skinning knife (attack 3): 2
0 - cancel
You've drunk Beer bottle

**Comment by Doktrjegih** [comment]
fixed, change the bug when bot wrongly checks inventory before skills upgrading
